### PR TITLE
isort black flake8 formatting

### LINKED ISSUE #3: isort black flake8 issue

### PR DESCRIPTION
**Pull request by saipradeep07**
flake8 nonstandardcode.py
Capture

### CODE REVIEW

**Review by Karthikeyaan-Kan — COMMENTED** [review]
Add shell output of flake8 command without errors in PR description

**Comment by saipradeep07** [comment]
> Add shell output of flake8 command without errors in PR description

**Comment by saipradeep07** [comment]
Capture

**Review by Karthikeyaan-Kan — APPROVED** [review]
The PR is approved

**Pull request merged**
